# Generated by Django 6.0.2 on 2026-03-13 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_subject_selected_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='study_end_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='subject',
            name='study_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
