# Generated by Django 6.0.2 on 2026-03-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_subject_study_end_time_subject_study_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={},
        ),
    ]
