# Generated by Django 6.0.2 on 2026-03-15 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_studysession_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['date']},
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['date'], name='planner_stu_date_f492fa_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['subject'], name='planner_stu_subject_7cac9c_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['user'], name='planner_sub_user_id_07e7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam_date'], name='planner_sub_exam_da_ceb593_idx'),
        ),
    ]
